# Generated by Django 5.1.7 on 2025-03-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dog",
            name="views_field",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите кол-во просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
    ]
